name: Build/Test Svelte/Rust App
# Inefficiencies:
# Runs build and test jobs for both dev and master
# if: contains(...) fail because artifacts are lost between runs
# Runs client and server builds when there are no changes

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    types: [closed]
    branches:
      - dev
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  Build-Production-Server:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2

      # - uses: hecrj/setup-rust-action@v1
      #   with:
      #     rust-version: nightly

      - uses: davidB/rust-cargo-make@v1

      - name: Cargo-Test
        run: cargo make test_server

      - name: Build-Server
        run: cargo make build_server

      - name: List-files
        run: pwd && ls -l target/release/err-test

      - name: Upload-Server-Artifact
        uses: actions/upload-artifact@v2
        with:
          name: server
          path: /home/runner/work/err-test/err-test/target/release/err-test
          if-no-files-found: error
          /Users/glen/Documents/Rust/err-test/target/release/err-test
